---

- name: Delete old Jenkins war file
  command: rm -rf /tmp/jenkins.war
  when: jenkins_version is defined

- name: Download Jenkins latest war apiVersion if specific version is not provided
  get_url:
    url: "{{ jenkins_pkg_url }}/latest/jenkins.war"
    dest: /tmp/jenkins.war
  when: jenkins_version is not defined

- name: Download Jenkins war apiVersion
  get_url:
    url: "{{ jenkins_pkg_url }}/download/war/{{ jenkins_version }}/jenkins.war"
    dest: /tmp/jenkins.war
  when: jenkins_version is defined

- name: Copy old war file to /tmp folder
  shell: yes | cp /usr/lib/jenkins/jenkins.war /tmp/jenkins.war.previous.version

- name: Copy the newly downloaded war file to the /usr/lib/jenkins directory
  shell: yes | cp /tmp/jenkins.war /usr/lib/jenkins/ 

- name: Stop the Jenkins service
  service:
    name: jenkins
    state: stopped

- name: Start the Jenkins service
  service:
    name: jenkins
    enabled: yes
    state: started
