---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not (lookup('env', 'MOLECULE_DEBUG') | bool or molecule_yml.provisioner.log|default(false) | bool) }}"
  vars_files:
    - vars.yml
  vars:
    role_name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
    aws_resource_name_tag_value: "{{ role_name }}-molecule-test-{{ branch }}-"
    keypair_path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
  tasks:
    - name: Get the current caller identity facts
      aws_caller_facts:
      register: caller_facts

    - name: Set the suffix in aws_resource_name_tag_value
      set_fact:
        aws_resource_name_tag_value: "{{ aws_resource_name_tag_value + suffix }}"
      vars:
        suffix: "{{ ansible_facts.ansible_machine_id | default(caller_facts.user_id.split(':')[1]) }}"

    - block:
        - name: Populate instance config
          set_fact:
            instance_conf: "{{ lookup('file', molecule_instance_config) | molecule_from_yaml }}"
            skip_instances: false
      rescue:
        - name: Populate instance config when file missing
          set_fact:
            instance_conf: {}
            skip_instances: true

    - name: Destroy molecule instance(s)
      ec2:
        state: absent
        region: "{{ region }}"
        instance_ids: "{{ item.instance_ids }}"
        wait: true
      register: server
      with_items: "{{ instance_conf }}"
      when: not skip_instances
      async: 7200
      poll: 0

    - name: Wait for instance(s) deletion to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: ec2_jobs
      until: ec2_jobs.finished
      retries: 300
      with_items: "{{ server.results }}"

    - name: Destroy molecule security group
      ec2_group:
        group_id: "{{ item.group_id }}"
        region: "{{ region }}"
        state: absent
      with_items: "{{ instance_conf }}"
      when: server.changed | bool # noqa 503

    - name: Delete local keypair
      file:
        path: "{{ keypair_path }}"
        state: absent

    - name: Delete remote keypair
      ec2_key:
        name: "{{ aws_resource_name_tag_value }}"
        region: "{{ region }}"
        state: absent

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool # noqa 503
