---

ssh_user: ec2-user
ssh_port: 22
branch: master
ami_id: ami-0c6b1d09930fac512
instance_type: t2.micro
vpc_subnet_id: subnet-0029daf13a2a612ca
vpc_id: vpc-06e3da71fc0780b68
region: us-east-1
security_group_rules:
  ingress:
    - proto: tcp
      from_port: 22
      to_port: 22
    - proto: tcp
      from_port: 8080
      to_port: 8080
    - proto: icmp
      from_port: 8
      to_port: -1
  egress:
    - proto: -1
      from_port: 0
      to_port: 0
      cidr_ip: '0.0.0.0/0'
