---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: docker-container
    image: amazonlinux:2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: docker
verifier:
  name: testinfra
  lint:
    name: flake8
